#微服务名
spring:
  application:
    name: product-data-service
  zipkin:
    base-url: http://localhost:9411
#和服务中心配置一致
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
#自己的端口
server:
  port: 8001
