#配置微服务注册中心
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
 #网关微服务 名
spring:
  application:
    name: product-service-zuul
#网关配置
zuul:
  routes:   #路由
    api-a:          #a接口
      path: /api-data/**  #路径相当于 http:ip:port + /api-data/**  比如,localhost:8022/api-date/products
      serviceId: PRODUCT-DATA-SERVICE
    api-b:         #b接口 映射以下路径和微服务
      path: /api-view/**
      serviceId: PRODUCT-VIEW-SERVICE-FEIGN

 #服务接口
server:
  port: 8022