spring:
  application.name: turbine          #微服务名
turbine:
  aggregator:
    clusterConfig: default
  appConfig: product-view-service-feign  # 配置Eureka中的serviceId列表，表明监控哪些服务
  clusterNameExpression: new String("default")
eureka:
  instance:
    hostname: localhost         #服务中心的地址 ip
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/   #url
server:
  port: 8021