#微服务名,以及thymeleaf设置
spring:
  application:
    name: product-view-service-ribbon
  zipkin:
    base-url: http://localhost:9411
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: /html
    servlet:
      content-type: text/html
    encoding: utf-8
    mode: html5
#和服务中心配置一致
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
#自己的端口
server:
  port: 8010
