#微服务名,以及thymeleaf设置
spring:
  application:
    name: product-view-service-feign
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    servlet:
      content-type: text/html
    encoding: utf-8
    mode: html5
  zipkin:
    base-url: http://localhost:9411

server:
  port: 8011
#允许访问路径 才能访问/actuator/bus-refresh
management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: * #gfgg
        allowed-methods: *